apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-rabbit-consumer
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-rabbit-consumer
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-rabbit-consumer
    spec:
      containers:
        - name: rabbit-consumer
          image: {{ .Values.image.rabbit_consumer.repository }}:{{ .Values.image.rabbit_consumer.tag }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          env:
            - name: RUST_LOG
              value: info
            - name: QUEUE_NAME
              value: direct_messages

          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq

      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-data
